In [5]:
import numpy as np

In [6]:
#data = np.loadtxt('data/movielens/ratings.dat', delimiter = '::', dtype=np.int64)
data = np.genfromtxt('./data/movielens/ratings.dat', delimiter = '::', dtype=np.int64)

## 데이터 컬럼 내용
# user_id :: item :: rating :: timestamp

In [7]:
# 5행까지 확인해보기
data[:6, :]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268]])

In [8]:
data.shape

(1000209, 4)

# 문제) 전체 평균 평점 계산하기

In [9]:
#데이터 컬럼 내용
#user_id :: item :: rating :: timestamp

In [10]:
mean_rating_total = data[:, 2].mean()

In [11]:
mean_rating_total

np.float64(3.581564453029317)

# 문제) 각 사용자 별 평균 평점 계산하기

In [12]:
#user_id에 대해 unique값만 먼저 뽑기
user_ids = np.unique(data[:,0])

In [13]:
user_ids[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
user_ids.shape

(6040,)

In [15]:
#빈 리스트 생성
mean_rating_by_user_list = []

for user_id in user_ids:
    data_for_user = data[data[:,0] == user_id, :]  #data_for_user는 특정 user_id 값들의 array를 저장한 변수 (unique값별로 저장)
    mean_rating_for_user = data_for_user[:, 2].mean()  # rating의 평균 
    mean_rating_by_user_list.append([user_id, mean_rating_for_user]) # 빈리스트에 값 넣기

In [16]:
data_for_user[:10]

array([[     6040,       573,         4, 956704056],
       [     6040,       589,         4, 956704996],
       [     6040,         1,         3, 957717358],
       [     6040,      2068,         4, 997453982],
       [     6040,       592,         2, 956716016],
       [     6040,       593,         5, 956703954],
       [     6040,      3016,         2, 956716157],
       [     6040,      3017,         1, 956716519],
       [     6040,      2070,         4, 956715676],
       [     6040,      1419,         3, 956704056]])

In [17]:
mean_rating_by_user_list[:10]

[[np.int64(1), np.float64(4.188679245283019)],
 [np.int64(2), np.float64(3.7131782945736433)],
 [np.int64(3), np.float64(3.9019607843137254)],
 [np.int64(4), np.float64(4.190476190476191)],
 [np.int64(5), np.float64(3.1464646464646466)],
 [np.int64(6), np.float64(3.9014084507042255)],
 [np.int64(7), np.float64(4.32258064516129)],
 [np.int64(8), np.float64(3.884892086330935)],
 [np.int64(9), np.float64(3.7358490566037736)],
 [np.int64(10), np.float64(4.114713216957606)]]

In [18]:
mean_rating_by_user_list_array = np.array(mean_rating_by_user_list, dtype=np.float64)

In [19]:
mean_rating_by_user_list_array.shape

(6040, 2)

# 파일에 writing하기

In [20]:
np.savetxt("./data/movielens/mean_rating_by_user.csv", mean_rating_by_user_list_array, fmt="%.3f", delimiter=',')